services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
    - ./frontend:/app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: noamfav061105!
      MYSQL_DATABASE: my_resume
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:latest
    environment:
      FLYWAY_URL: jdbc:mysql://db:3306/my_resume?useSSL=false&allowPublicKeyRetrieval=true
      FLYWAY_USER: root
      FLYWAY_PASSWORD: noamfav061105!
    command: migrate
    volumes:
      - ./migrations:/flyway/sql  # Ensure your migration files are placed here
    depends_on:
      db:
        condition: service_healthy  # Ensures Flyway only runs when MySQL is ready
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
