// Builds the CV from the same JSON the site reads, so the three never drift:
//
//   node cv/build.mjs            resume.tex, resume-anon.tex and RESUME.md in cv/
//   node cv/build.mjs --pdf      also runs xelatex and copies resume.pdf to public/
//
// Content that only the CV has (summary, spoken languages, which projects make
// the one page) lives in public/data/profile.json.
import { readFileSync, writeFileSync, copyFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { figlet } from "../src/ui/figlet-font.js";
import { formatDate, sha, byRecent, isOngoing } from "../src/lib/format.js";

const here = dirname(fileURLToPath(import.meta.url));
const data = (name) => JSON.parse(readFileSync(join(here, "../public/data", `${name}.json`), "utf8"));

const profile = data("profile");
const { contact, social } = data("contact");
const { experience } = data("experience");
const { project: projects } = data("projects");
const { programming_language: languages } = data("programming_languages");
const cv = profile.cv;

const host = (url) => url.replace(/^https?:\/\//, "").replace(/\/$/, "");
const range = (a, b) => {
    const from = formatDate(a);
    const to = b ? formatDate(b) : "now";
    return from === to ? from : `${from} – ${to}`;
};

// "Company" or "Company/Position", in the order profile.json lists them
const roles = cv.experience.map((key) => {
    const [company, position] = key.split("/");
    const hit = experience.find((e) => e.company === company && (!position || e.position === position));
    if (!hit) throw new Error(`profile.json: no experience entry for "${key}"`);
    return hit;
}).sort(byRecent);

const featured = cv.projects.map((p) => ({ ...projects.find((x) => x.title === p.title), ...p }));
const meters = cv.languages.map((name) => languages.find((l) => l.name === name));

// ── LaTeX ─────────────────────────────────────────────────────────────────
const TEX = { "\\": "\\textbackslash{}", "&": "\\&", "%": "\\%", $: "\\$", "#": "\\#", _: "\\_",
    "{": "\\{", "}": "\\}", "~": "\\textasciitilde{}", "^": "\\textasciicircum{}" };
const esc = (s) => String(s).replace(/[\\&%$#_{}~^]/g, (c) => TEX[c]);
// Prose: escape, then `code` spans become \code{}
const prose = (s) => String(s).split(/`([^`]+)`/).map((p, i) => (i % 2 ? `\\code{${esc(p)}}` : esc(p))).join("");

function tex(anon) {
    const pick = (o, key) => (anon && o[`${key}_anon`]) || o[key];
    const scrub = (s) => (anon ? Object.entries(cv.anon.replace).reduce((t, [a, b]) => t.replaceAll(a, b), s) : s);
    const out = [];
    const put = (...lines) => out.push(...lines);

    put(
        "% Generated by cv/build.mjs from public/data — edit the JSON, not this file.",
        "\\documentclass{nfcv}",
        anon ? "\\cvbrand{anon}{cv}" : `\\cvbrand{${profile.handle.toLowerCase()}}{nf}`,
        "\\cvwindows{resume}{experience,projects,skills,education}",
        `\\cvstatus{\\textasciitilde/${anon ? "cv" : "noam-favier"}.pdf}{${anon ? "references on request" : esc(contact.address)}}`,
        "\\begin{document}",
        "",
    );

    // Header: banner and whoami on the left, fetch readout on the right
    put("\\begin{minipage}[b]{0.6\\linewidth}", "\\begin{cvbanner}[6.1pt]");
    for (const row of figlet(anon ? "CV" : profile.name)) put(`\\bannerline{${row.replaceAll(" ", ".")}}`);
    put("\\end{cvbanner}", "\\vspace{5pt}",
        `\\prompt{whoami}\\par {\\bfseries ${esc(profile.tagline)}}\\par\\vspace{3pt}`,
        `{\\serif\\small\\raggedright\\color{nf-muted} ${esc(anon ? profile.summary_anon : profile.summary)}\\par}`,
        "\\end{minipage}\\hfill",
        "\\begin{minipage}[b]{0.34\\linewidth}",
        "\\begin{pane}[fetch]{sys}", "\\begin{cvfetch}[5.4em]");
    if (!anon) {
        put(`\\fetch{mail}{\\href{mailto:${contact.email}}{${esc(contact.email)}}}`,
            `\\fetch{web}{\\href{${social.website}}{${esc(host(social.website))}}}`,
            `\\fetch{github}{\\href{${social.github}}{${esc(host(social.github))}}}`,
            `\\fetch{linkedin}{\\href{${social.linkedin}}{in/noam-favier}}`,
            `\\fetch{resume}{\\href{https://noamfav.github.io/Resume/}{noamfav.github.io/Resume}}`,
            `\\fetch{loc}{${esc(contact.address)}}`);
    }
    put(`\\fetch{origin}{${esc(profile.nationality)}}`,
        "\\fetch{theme}{\\swatches}",
        "\\end{cvfetch}", "\\end{pane}", "\\end{minipage}", "",
        "\\columnratio{0.635}", "\\setlength\\columnsep{7mm}", "\\begin{paracol}{2}", "");

    // Left column
    put("\\cvsection[git log --graph]{01}{experience}");
    for (const r of roles) {
        const refs = isOngoing(r.end_date) ? "HEAD -> main" : "";
        const where = [scrub(r.company), r.location].filter(Boolean).join(" · ");
        put(`\\commit[${refs}]{${sha(r.company + r.position)}}{${range(r.start_date, r.end_date)}}` +
            `{${esc(r.position)}}{${esc(where)}}{${prose(scrub(pick(r, "details") ?? r.description))}}`);
    }
    put("", "\\cvsection[ls \\textasciitilde{}/code]{02}{projects}");
    for (const p of featured) {
        const langs = (p.languages ?? []).slice(0, 3).join(", ");
        put(`\\entry{${esc(pick(p, "title"))}/}{${prose(p.role)}${langs ? ` · ${esc(langs)}` : ""}}{${prose(pick(p, "text"))}}`);
    }
    put("", "\\cvsection[university]{03}{academic}");
    for (const a of cv.academic) {
        put(`\\entry{${esc(a.title)}/}{${esc(a.role)} · ${esc(a.dates)}}{${prose(a.text)}}`);
    }

    // Right column
    put("", "\\switchcolumn", "\\cvsection[htop]{04}{skills}");
    for (const m of meters) put(`\\meter[6.4em]{${esc(m.name)}}{${m.percentage}}`);
    put("\\vspace{5pt}", "\\begin{cvfetch}[5.4em]",
        `\\fetch{primary}{${esc(cv.stack.primary)}}`,
        `\\fetch{also}{${esc(cv.stack.advanced)}}`,
        `\\fetch{tools}{${esc(cv.stack.tools)}}`,
        "\\end{cvfetch}\\vspace{4pt}",
        `{\\linespread{1.5}\\selectfont ${cv.expertise.map((e) => `\\tag{${esc(e)}}`).join(" ")}\\par}`,
        "", "\\cvsection[cat \\textasciitilde{}/.edu]{05}{education}");
    for (const e of cv.education) put(`\\entry{${esc(e.title)}}{}{${esc(e.line)}${e.note ? `\\\\ ${esc(e.note)}` : ""}}`);
    put("", "\\cvsection[locale -a]{06}{languages}", "\\begin{cvfetch}[3.4em]");
    for (const l of profile.spoken) {
        put(`\\fetch{${l.code.replace("_", "\\_")}}{\\makebox[1.6em][l]{\\bfseries ${l.level}}\\textcolor{nf-muted}{${esc(l.name)}${l.note ? `, ${esc(l.note)}` : ""}}}`);
    }
    put("\\end{cvfetch}", "", "\\cvsection[ls \\textasciitilde{}/certs]{07}{also}");
    const soft = cv.soft.filter((s) => !(anon && s.personal)).map((s) => esc(s.text));
    put(`{\\color{nf-muted}${cv.certifications.map(esc).join(" · ")}\\par\\vspace{3pt}${soft.join(" · ")}\\par}`,
        "\\vspace{8pt}",
        `{\\itshape\\textcolor{nf-dim}{\\# ${esc(profile.philosophy)}}\\par}`,
        "", "\\end{paracol}", "\\end{document}", "");
    return out.join("\n");
}

// ── Markdown, for READMEs (a GitHub profile, a repo's about) ─────────────────
function md() {
    const banner = figlet(profile.name).join("\n");
    const lines = [
        "<!-- Generated by cv/build.mjs from public/data — edit the JSON, not this file. -->",
        "", "```text", banner, "```", "",
        `> \`$ whoami\` — **${profile.tagline}**`, "",
        profile.summary, "",
        "```text",
        `mail      ${contact.email}`,
        `web       ${host(social.website)}`,
        `github    ${host(social.github)}`,
        `loc       ${contact.address}`,
        `resume    noamfav.github.io/Resume`,
        "```", "",
        "## `01` experience", "",
    ];
    for (const r of roles) {
        const refs = isOngoing(r.end_date) ? " `(HEAD -> main)`" : "";
        lines.push(`- \`${sha(r.company + r.position)}\`${refs} **${r.position}** @ ${r.company} · ${range(r.start_date, r.end_date)}  `,
            `  ${r.details ?? r.description}`);
    }
    lines.push("", "## `02` projects", "", "| | | |", "| --- | --- | --- |");
    for (const p of featured) {
        const link = p.git_url ? `[${p.title}/](${p.git_url})` : `${p.title}/`;
        lines.push(`| **${link}** | ${p.role} | ${p.text.replaceAll("|", "\\|")} |`);
    }
    lines.push("", "## `03` skills", "", "```text");
    const width = 24;
    for (const m of meters) {
        const fill = Math.round((m.percentage / 100) * width);
        lines.push(`${m.name.padEnd(11)}[${"|".repeat(fill)}${" ".repeat(width - fill)} ${String(m.percentage).padStart(3)}%]`);
    }
    lines.push("```", "", `**tools** ${cv.stack.tools}`, "", "## `04` education", "");
    for (const e of cv.education) lines.push(`- **${e.title}** · ${e.line}${e.note ? ` — ${e.note}` : ""}`);
    lines.push("", `**languages** ${profile.spoken.map((l) => `${l.name} ${l.level}`).join(" · ")}  `,
        `**certs** ${cv.certifications.join(" · ")}`, "", `<sub><i># ${profile.philosophy}</i></sub>`, "");
    return lines.join("\n");
}

writeFileSync(join(here, "resume.tex"), tex(false));
writeFileSync(join(here, "resume-anon.tex"), tex(true));
writeFileSync(join(here, "RESUME.md"), md());
console.log("cv: wrote resume.tex, resume-anon.tex, RESUME.md");

if (process.argv.includes("--pdf")) {
    for (const name of ["resume", "resume-anon"]) {
        // twice: the statusline reads the page count from the .aux
        for (let i = 0; i < 2; i++) {
            execFileSync("xelatex", ["-interaction=nonstopmode", "-halt-on-error", "-output-directory=build", `${name}.tex`],
                { cwd: here, stdio: i ? "inherit" : "ignore" });
        }
    }
    copyFileSync(join(here, "build/resume.pdf"), join(here, "../public/resume.pdf"));
    console.log("cv: public/resume.pdf updated");
}
